_wandb:
    value:
        cli_version: 0.25.0
        e:
            afx2sdm1m1js27wwsp1jlcepob4041cu:
                codePath: script/smoke_test_collect.py
                codePathLocal: script/smoke_test_collect.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "64424509440"
                        used: "16463405056"
                email: qifan_wen@outlook.com
                executable: /usr/bin/python3
                git:
                    commit: f82be32fdb1def94c8631c52d36ccb880b2cb1dd
                    remote: git@github.com:Albatross679/snake-hrl-torchrl.git
                gpu: Tesla V100-PCIE-16GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "17179869184"
                      name: Tesla V100-PCIE-16GB
                      uuid: GPU-fa78a34c-8eeb-40f2-9722-c931b34764cc
                host: 1878b53519e6
                memory:
                    total: "270328070144"
                os: Linux-5.4.0-216-generic-x86_64-with-glibc2.39
                program: /home/coder/snake-hrl-torchrl/script/smoke_test_collect.py
                python: CPython 3.12.3
                root: /home/coder/snake-hrl-torchrl
                startedAt: "2026-03-09T18:28:05.461542Z"
                writerId: afx2sdm1m1js27wwsp1jlcepob4041cu
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 16
            "4": 3.12.3
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
baseline_fps:
    value: null
num_transitions:
    value: 1000
num_workers:
    value: 2
perturbation_fraction:
    value: 0.3
save_dir:
    value: data/tmp_smoke_test
seed:
    value: 12345
use_sobol_actions:
    value: true
