_wandb:
    value:
        cli_version: 0.25.0
        e:
            lis8k5gmhof6s6mq9k6vd8kz8ogvax1h:
                args:
                    - --steps-per-run
                    - "1"
                    - --collect-forces
                    - --save-dir
                    - data/surrogate_rl_step
                    - --num-workers
                    - "16"
                    - --num-transitions
                    - "50000000"
                    - --episodes-per-save
                    - "100"
                    - --perturbation-fraction
                    - "0.3"
                    - --perturb-omega-std
                    - "1.5"
                    - --sobol
                    - --seed
                    - "43"
                    - --skip-disk-check
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "64424509440"
                        used: "19497799680"
                email: qifan_wen@outlook.com
                executable: /usr/bin/python3
                git:
                    commit: 4202b0712a3fdba48cf729990c6f44d97ca0d406
                    remote: git@github.com:Albatross679/snake-hrl-torchrl.git
                gpu: Tesla V100-PCIE-16GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "17179869184"
                      name: Tesla V100-PCIE-16GB
                      uuid: GPU-fa78a34c-8eeb-40f2-9722-c931b34764cc
                host: 1878b53519e6
                memory:
                    total: "270328070144"
                os: Linux-5.4.0-216-generic-x86_64-with-glibc2.39
                program: -m aprx_model_elastica.__main__
                python: CPython 3.12.3
                root: /home/coder/snake-hrl-torchrl
                startedAt: "2026-03-10T15:30:26.339447Z"
                writerId: lis8k5gmhof6s6mq9k6vd8kz8ogvax1h
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
baseline_fps:
    value: null
collect_forces:
    value: true
flat_output:
    value: true
num_transitions:
    value: 50000000
num_workers:
    value: 16
perturb_omega_std:
    value: 1.5
perturbation_fraction:
    value: 0.3
save_dir:
    value: data/surrogate_rl_step
seed:
    value: 43
use_sobol_actions:
    value: true
