"""Central Pattern Generator oscillators for rhythmic locomotion control.

This module provides neural oscillator implementations for generating
rhythmic curvature patterns that drive snake locomotion.

Key classes:
    - MatsuokaOscillator: Single Matsuoka neural oscillator
    - HopfOscillator: Hopf bifurcation oscillator
    - CPGNetwork: Coupled oscillator network
"""

from typing import Optional, Tuple, List
import numpy as np


class MatsuokaOscillator:
    """Matsuoka neural oscillator for rhythm generation.

    The Matsuoka oscillator consists of two mutually inhibiting neurons
    that produce sustained oscillations. The dynamics are:

        tau * dx1/dt = -x1 - b*v1 - w12*y2 + u
        tau' * dv1/dt = -v1 + y1
        y1 = max(0, x1)

    (and similarly for neuron 2)

    The output is typically y1 - y2, producing a symmetric oscillation.

    Reference:
        Matsuoka, K. (1985). Sustained oscillations generated by mutually
        inhibiting neurons with adaptation.
    """

    def __init__(
        self,
        tau: float = 0.1,
        tau_prime: float = 0.5,
        b: float = 2.5,
        w: float = 2.5,
        u: float = 1.0,
    ):
        """Initialize Matsuoka oscillator.

        Args:
            tau: Time constant for membrane potential
            tau_prime: Time constant for adaptation (tau' > tau for oscillation)
            b: Adaptation coefficient (controls amplitude damping)
            w: Mutual inhibition weight (controls coupling strength)
            u: External input (tonic drive)
        """
        self.tau = tau
        self.tau_prime = tau_prime
        self.b = b
        self.w = w
        self.u = u

        # State variables: [x1, v1, x2, v2]
        self.state = np.array([1.0, 0.0, -1.0, 0.0])

        # Outputs
        self.y1 = 0.0
        self.y2 = 0.0

    def reset(self, phase: float = 0.0) -> None:
        """Reset oscillator state with optional phase offset.

        Args:
            phase: Phase offset in radians (0 = default, pi = anti-phase)
        """
        if phase < np.pi:
            self.state = np.array([1.0, 0.0, -1.0, 0.0])
        else:
            self.state = np.array([-1.0, 0.0, 1.0, 0.0])
        self.y1 = max(0, self.state[0])
        self.y2 = max(0, self.state[2])

    def step(self, dt: float, u: Optional[float] = None) -> float:
        """Advance oscillator by one timestep.

        Args:
            dt: Timestep size
            u: Optional external input (uses default if None)

        Returns:
            Oscillator output (y1 - y2), normalized to approximately [-1, 1]
        """
        if u is None:
            u = self.u

        x1, v1, x2, v2 = self.state

        # Compute outputs (ReLU)
        self.y1 = max(0, x1)
        self.y2 = max(0, x2)

        # Compute derivatives
        dx1 = (-x1 - self.b * v1 - self.w * self.y2 + u) / self.tau
        dv1 = (-v1 + self.y1) / self.tau_prime
        dx2 = (-x2 - self.b * v2 - self.w * self.y1 + u) / self.tau
        dv2 = (-v2 + self.y2) / self.tau_prime

        # Euler integration
        self.state += dt * np.array([dx1, dv1, dx2, dv2])

        # Return normalized output
        output = self.y1 - self.y2
        return output

    @property
    def output(self) -> float:
        """Get current oscillator output."""
        return self.y1 - self.y2

    @property
    def frequency(self) -> float:
        """Approximate oscillation frequency (depends on parameters)."""
        # Empirical approximation
        return 1.0 / (2 * np.pi * np.sqrt(self.tau * self.tau_prime))


class HopfOscillator:
    """Hopf bifurcation oscillator for smooth limit cycle dynamics.

    The Hopf oscillator produces smooth sinusoidal oscillations with
    controllable amplitude and frequency:

        dx/dt = mu*(r^2 - x^2 - y^2)*x - omega*y
        dy/dt = mu*(r^2 - x^2 - y^2)*y + omega*x

    where r is the target amplitude and omega is the angular frequency.

    Advantages:
        - Smooth, sinusoidal output
        - Explicit amplitude and frequency control
        - Robust limit cycle dynamics
    """

    def __init__(
        self,
        amplitude: float = 1.0,
        frequency: float = 1.0,
        mu: float = 10.0,
    ):
        """Initialize Hopf oscillator.

        Args:
            amplitude: Target oscillation amplitude (r)
            frequency: Oscillation frequency in Hz
            mu: Convergence rate to limit cycle
        """
        self.amplitude = amplitude
        self.frequency = frequency
        self.omega = 2 * np.pi * frequency
        self.mu = mu

        # State: [x, y]
        self.state = np.array([amplitude, 0.0])

    def reset(self, phase: float = 0.0) -> None:
        """Reset oscillator state with optional phase offset.

        Args:
            phase: Phase offset in radians
        """
        self.state = np.array([
            self.amplitude * np.cos(phase),
            self.amplitude * np.sin(phase),
        ])

    def set_parameters(self, amplitude: float, frequency: float) -> None:
        """Update oscillator parameters.

        Args:
            amplitude: New target amplitude
            frequency: New frequency in Hz
        """
        self.amplitude = amplitude
        self.frequency = frequency
        self.omega = 2 * np.pi * frequency

    def step(self, dt: float) -> float:
        """Advance oscillator by one timestep.

        Args:
            dt: Timestep size

        Returns:
            Oscillator output (x component), in range [-amplitude, amplitude]
        """
        x, y = self.state
        r_sq = x * x + y * y
        target_r_sq = self.amplitude * self.amplitude

        # Compute derivatives
        dx = self.mu * (target_r_sq - r_sq) * x - self.omega * y
        dy = self.mu * (target_r_sq - r_sq) * y + self.omega * x

        # Euler integration
        self.state += dt * np.array([dx, dy])

        return self.state[0]

    @property
    def output(self) -> float:
        """Get current oscillator output (x component)."""
        return self.state[0]

    @property
    def phase(self) -> float:
        """Get current oscillator phase in radians."""
        return np.arctan2(self.state[1], self.state[0])


class CPGNetwork:
    """Network of coupled oscillators for coordinated locomotion patterns.

    The CPG network produces phase-locked oscillations at multiple points
    along the snake body. The phase relationships between oscillators
    determine the wave propagation direction and wavelength.

    Architecture:
        - Chain of oscillators with nearest-neighbor coupling
        - Phase offsets create traveling wave patterns
        - Output is interpolated to match number of joints
    """

    def __init__(
        self,
        num_oscillators: int = 4,
        oscillator_type: str = "matsuoka",
        coupling_strength: float = 1.0,
        base_frequency: float = 1.0,
    ):
        """Initialize CPG network.

        Args:
            num_oscillators: Number of oscillators in the network
            oscillator_type: "matsuoka" or "hopf"
            coupling_strength: Inter-oscillator coupling strength
            base_frequency: Base oscillation frequency
        """
        self.num_oscillators = num_oscillators
        self.oscillator_type = oscillator_type
        self.coupling_strength = coupling_strength
        self.base_frequency = base_frequency

        # Create oscillators
        self.oscillators: List = []
        for i in range(num_oscillators):
            if oscillator_type == "matsuoka":
                osc = MatsuokaOscillator(tau=0.1, tau_prime=0.5)
            else:  # hopf
                osc = HopfOscillator(amplitude=1.0, frequency=base_frequency)
            self.oscillators.append(osc)

        # Phase offsets for wave propagation
        self._phase_offsets = np.linspace(0, 2 * np.pi, num_oscillators, endpoint=False)

        # Initialize with phase offsets
        self.reset()

    def reset(self, initial_phase: float = 0.0) -> None:
        """Reset all oscillators with appropriate phase offsets.

        Args:
            initial_phase: Global phase offset
        """
        for i, osc in enumerate(self.oscillators):
            phase = initial_phase + self._phase_offsets[i]
            osc.reset(phase=phase)

    def set_parameters(
        self,
        amplitude: float,
        frequency: float,
        wave_number: float,
    ) -> None:
        """Set CPG parameters from high-level gait parameters.

        Args:
            amplitude: Overall amplitude (controls curvature magnitude)
            frequency: Oscillation frequency (controls speed)
            wave_number: Number of waves along body (controls wavelength)
        """
        # Update phase offsets based on wave number
        total_phase = 2 * np.pi * wave_number
        self._phase_offsets = np.linspace(0, total_phase, self.num_oscillators, endpoint=False)

        # Update individual oscillators
        for i, osc in enumerate(self.oscillators):
            if isinstance(osc, HopfOscillator):
                osc.set_parameters(amplitude, frequency)
            # Matsuoka uses external input for amplitude control

    def step(self, dt: float, amplitude: float = 1.0) -> np.ndarray:
        """Advance all oscillators by one timestep.

        Args:
            dt: Timestep size
            amplitude: Amplitude scaling factor

        Returns:
            Array of oscillator outputs, shape (num_oscillators,)
        """
        outputs = np.zeros(self.num_oscillators)

        for i, osc in enumerate(self.oscillators):
            if isinstance(osc, MatsuokaOscillator):
                outputs[i] = osc.step(dt, u=amplitude)
            else:
                outputs[i] = osc.step(dt)

        return outputs * amplitude

    def get_joint_curvatures(
        self,
        outputs: np.ndarray,
        num_joints: int,
        amplitude: float = 1.0,
    ) -> np.ndarray:
        """Interpolate oscillator outputs to joint curvatures.

        Args:
            outputs: Oscillator outputs, shape (num_oscillators,)
            num_joints: Number of joints to interpolate to (e.g., 19)
            amplitude: Amplitude scaling factor

        Returns:
            Target curvatures for each joint, shape (num_joints,)
        """
        if len(outputs) == num_joints:
            return outputs * amplitude

        # Interpolate to num_joints
        osc_positions = np.linspace(0, 1, self.num_oscillators)
        joint_positions = np.linspace(0, 1, num_joints)

        curvatures = np.interp(joint_positions, osc_positions, outputs)
        return curvatures * amplitude

    @property
    def outputs(self) -> np.ndarray:
        """Get current outputs from all oscillators."""
        return np.array([osc.output for osc in self.oscillators])


class AdaptiveCPGNetwork(CPGNetwork):
    """CPG network with online adaptation of parameters.

    Extends CPGNetwork with mechanisms for adapting parameters based on
    sensory feedback, enabling more robust locomotion in varying conditions.
    """

    def __init__(
        self,
        num_oscillators: int = 4,
        oscillator_type: str = "hopf",
        coupling_strength: float = 1.0,
        base_frequency: float = 1.0,
        adaptation_rate: float = 0.1,
    ):
        """Initialize adaptive CPG network.

        Args:
            num_oscillators: Number of oscillators
            oscillator_type: Oscillator type
            coupling_strength: Coupling strength
            base_frequency: Base frequency
            adaptation_rate: Rate of parameter adaptation
        """
        super().__init__(
            num_oscillators,
            oscillator_type,
            coupling_strength,
            base_frequency,
        )
        self.adaptation_rate = adaptation_rate

        # Adaptive parameters
        self._target_amplitude = 1.0
        self._target_frequency = base_frequency
        self._current_amplitude = 1.0
        self._current_frequency = base_frequency

    def adapt_parameters(
        self,
        target_amplitude: float,
        target_frequency: float,
        dt: float,
    ) -> None:
        """Smoothly adapt parameters toward targets.

        Args:
            target_amplitude: Target amplitude
            target_frequency: Target frequency
            dt: Timestep for adaptation
        """
        self._target_amplitude = target_amplitude
        self._target_frequency = target_frequency

        # Exponential smoothing
        alpha = 1 - np.exp(-self.adaptation_rate * dt)
        self._current_amplitude += alpha * (target_amplitude - self._current_amplitude)
        self._current_frequency += alpha * (target_frequency - self._current_frequency)

        # Update oscillators
        for osc in self.oscillators:
            if isinstance(osc, HopfOscillator):
                osc.set_parameters(self._current_amplitude, self._current_frequency)

    def step_with_adaptation(
        self,
        dt: float,
        target_amplitude: float,
        target_frequency: float,
    ) -> np.ndarray:
        """Step with parameter adaptation.

        Args:
            dt: Timestep
            target_amplitude: Target amplitude
            target_frequency: Target frequency

        Returns:
            Oscillator outputs
        """
        self.adapt_parameters(target_amplitude, target_frequency, dt)
        return self.step(dt, amplitude=self._current_amplitude)
