_wandb:
    value:
        cli_version: 0.25.0
        e:
            x9c1ipiplcsl9nlrtti9oh0m5hwydwjp:
                args:
                    - --steps-per-run
                    - "1"
                    - --collect-forces
                    - --save-dir
                    - /tmp/surrogate_rl_step_smoke
                    - --num-workers
                    - "1"
                    - --num-transitions
                    - "10"
                    - --episodes-per-save
                    - "10"
                    - --perturbation-fraction
                    - "0.3"
                    - --perturb-omega-std
                    - "1.5"
                    - --sobol
                    - --seed
                    - "43"
                    - --skip-disk-check
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "64424509440"
                        used: "19498061824"
                email: qifan_wen@outlook.com
                executable: /usr/bin/python3
                git:
                    commit: 5563925652f21fe2238c65c69912baea6c580c1e
                    remote: git@github.com:Albatross679/snake-hrl-torchrl.git
                gpu: Tesla V100-PCIE-16GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "17179869184"
                      name: Tesla V100-PCIE-16GB
                      uuid: GPU-fa78a34c-8eeb-40f2-9722-c931b34764cc
                host: 1878b53519e6
                memory:
                    total: "270328070144"
                os: Linux-5.4.0-216-generic-x86_64-with-glibc2.39
                program: -m aprx_model_elastica.__main__
                python: CPython 3.12.3
                root: /home/coder/snake-hrl-torchrl
                startedAt: "2026-03-10T15:28:57.037864Z"
                writerId: x9c1ipiplcsl9nlrtti9oh0m5hwydwjp
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
collect_forces:
    value: true
flat_output:
    value: true
num_transitions:
    value: 10
num_workers:
    value: 1
perturb_omega_std:
    value: 1.5
perturbation_fraction:
    value: 0.3
seed:
    value: 43
steps_per_run:
    value: 1
